// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAqMOzOz0doIFUereSQ_oT041UWeXYo03Q',
//     appId: '1:314975598607:web:8073df0d67a19049d50b7a',
//     messagingSenderId: '314975598607',
//     projectId: 'learn-traffic-rules-cbbd1',
//     authDomain: 'learn-traffic-rules-cbbd1.firebaseapp.com',
//     storageBucket: 'learn-traffic-rules-cbbd1.firebasestorage.app',
//     measurementId: 'G-S533N8J4QP',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDeolWMXeHnp-Ps6Nt_GYp0lu1B44Yy4wY',
//     appId: '1:314975598607:android:b9c8c27f9f6a227cd50b7a',
//     messagingSenderId: '314975598607',
//     projectId: 'learn-traffic-rules-cbbd1',
//     storageBucket: 'learn-traffic-rules-cbbd1.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBu0OhD8vLGHlPKCo-QdVE5t5_R-ppv6XA',
//     appId: '1:314975598607:ios:3557f7089aa0a7bbd50b7a',
//     messagingSenderId: '314975598607',
//     projectId: 'learn-traffic-rules-cbbd1',
//     storageBucket: 'learn-traffic-rules-cbbd1.firebasestorage.app',
//     iosBundleId: 'com.example.learnTrafficRules',
//   );
// }
